/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicTable: typeof import('./../src/components/Table/src/BasicTable.vue')['default']
    ColumnSetting: typeof import('./../src/components/Table/src/components/settings/ColumnSetting.vue')['default']
    Components: typeof import('./../src/components/index.vue')['default']
    CountTo: typeof import('./../src/components/CountTo.vue')['default']
    EditableCell: typeof import('./../src/components/Table/src/components/editable/EditableCell.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    NaiveProvider: typeof import('./../src/components/NaiveProvider/index.vue')['default']
    NaiveProviderContent: typeof import('./../src/components/NaiveProvider/NaiveProviderContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableAction: typeof import('./../src/components/Table/src/components/TableAction.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanContactCard: typeof import('vant/es')['ContactCard']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VantProvider: typeof import('./../src/components/VantProvider.vue')['default']
  }
}
