// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BasicTable: typeof import('./src/components/common/Table/src/BasicTable.vue')['default']
    ColumnSetting: typeof import('./src/components/common/Table/src/components/settings/ColumnSetting.vue')['default']
    CountTo: typeof import('./src/components/common/CountTo/index.vue')['default']
    EditableCell: typeof import('./src/components/common/Table/src/components/editable/EditableCell.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider/index.vue')['default']
    NaiveProviderContent: typeof import('./src/components/common/NaiveProvider/NaiveProviderContent.vue')['default']
    SvgIcon: typeof import('./src/components/common/Icons/SvgIcon.vue')['default']
    TableAction: typeof import('./src/components/common/Table/src/components/TableAction.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanActionBarIcon: typeof import('vant/es')['ActionBarIcon']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanContactCard: typeof import('vant/es')['ContactCard']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}

export { }
